# Generated by Django 4.1.6 on 2023-02-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
