# Generated by Django 4.1.6 on 2023-02-12 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0005_rename_dercricao_pet_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='fotos',
            new_name='foto',
        ),
    ]
